# Generated by Django 6.0.6 on 2026-07-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('text', models.TextField()),
                ('expected_answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_score', models.IntegerField(default=0)),
                ('writing_score', models.IntegerField(default=0)),
                ('comprehension_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
            ],
        ),
    ]
