# Generated by Django 6.0.6 on 2026-07-06 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='created_at',
            new_name='completedAt',
        ),
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='comprehension_score',
            new_name='comprehensionScore',
        ),
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='overall_score',
            new_name='overallScore',
        ),
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='reading_score',
            new_name='readingScore',
        ),
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='writing_score',
            new_name='writingScore',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='assigned_level',
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
