export interface VocabItem {
  emoji: string;
  english: string;
  translations: Record<string, string>;
  image?: string;
}

export const vocabCategories: Record<string, VocabItem[]> = {
  'Fruits & Food': [
    { emoji: '🍎', english: 'Apple', translations: { hindi: 'सेब (Seb)', tamil: 'ஆப்பிள் (Āppiḷ)', telugu: 'ఆపిల్ (Āpil)', kannada: 'ಸೇಬು (Sēbu)' }, image: '/vocab_apple.png' },
    { emoji: '🍌', english: 'Banana', translations: { hindi: 'केला (Kela)', tamil: 'வாழைப்பழம் (Vāḻaippaḻam)', telugu: 'అరటిపండు (Araṭipaṇḍu)', kannada: 'ಬಾಳೆಹಣ್ಣು (Bāḷehaṇṇu)' }, image: '/vocab_banana.png' },
    { emoji: '🥛', english: 'Milk', translations: { hindi: 'दूध (Doodh)', tamil: 'பால் (Pāl)', telugu: 'పాలు (Pālu)', kannada: 'ಹಾಲು (Hālu)' } },
    { emoji: '🍞', english: 'Bread', translations: { hindi: 'रोटी (Roti)', tamil: 'ರொட்டி (Roṭṭi)', telugu: 'రొట్టె (Roṭṭe)', kannada: 'ರೊಟ್ಟಿ (Roṭṭi)' } },
    { emoji: '🥚', english: 'Egg', translations: { hindi: 'अंडा (Anda)', tamil: 'முட்டை (Muṭṭai)', telugu: 'గుడ్డు (Guḍḍu)', kannada: 'ಮೊಟ್ಟೆ (Moṭṭe)' } },
    { emoji: '💧', english: 'Water', translations: { hindi: 'पानी (Paani)', tamil: 'தண்ணீர் (Taṇṇīr)', telugu: 'నీరు (Nīru)', kannada: 'ನೀರು (Nīru)' } },
    { emoji: '🍚', english: 'Rice', translations: { hindi: 'चावल (Chawal)', tamil: 'அரிசி (Arici)', telugu: 'బియ్యం (Biyyaṁ)', kannada: 'ಅಕ್ಕಿ (Akki)' } },
    { emoji: '🧈', english: 'Butter', translations: { hindi: 'मक्खन (Makkhan)', tamil: 'வெண்ணெய் (Veṇṇey)', telugu: 'వెన్న (Venna)', kannada: 'ಬೆಣ್ಣೆ (Beṇṇe)' } },
    { emoji: '🧀', english: 'Cheese', translations: { hindi: 'पनीर (Paneer)', tamil: 'பாலாடைக்கட்டி', telugu: 'జున్ను (Junnu)', kannada: 'ಗಿಣ್ಣು (Giṇṇu)' } },
    { emoji: '🍇', english: 'Grapes', translations: { hindi: 'अंगूर (Angoor)', tamil: 'திராட்சை (Tirāṭcai)', telugu: 'ద్రాక్ష (Drākṣa)', kannada: 'ದ್ರಾಕ್ಷಿ (Drākṣi)' } },
    { emoji: '🥔', english: 'Potato', translations: { hindi: 'आलू (Aloo)', tamil: 'உருளைக்கிழங்கு', telugu: 'బంగాళదుంప', kannada: 'ಆಲೂಗಡ್ಡೆ' } },
    { emoji: '🍅', english: 'Tomato', translations: { hindi: 'टमाटर (Tamatar)', tamil: 'தக்காளி (Takkāḷi)', telugu: 'టమోటా (Tamōṭā)', kannada: 'ಟೊಮೆಟೊ (Tomato)' } },
    { emoji: '🧅', english: 'Onion', translations: { hindi: 'प्याज (Pyaz)', tamil: 'வெங்காயம் (Veṅkāyam)', telugu: 'ఉల్లిపాయ (Ullipāya)', kannada: 'ಈರುಳ್ಳಿ (Īruḷḷi)' } },
    { emoji: '🥭', english: 'Mango', translations: { hindi: 'आम (Aam)', tamil: 'மாம்பழம் (Māmpaḻam)', telugu: 'మామిడిపండు', kannada: 'ಮಾವಿನಹಣ್ಣು' } },
    { emoji: '🍋', english: 'Lemon', translations: { hindi: 'नींबू (Nimboo)', tamil: 'எலுமிச்சை (Elumiccai)', telugu: 'నిమ్మకాయ (Nimmakāya)', kannada: 'ನಿಂಬೆಹಣ್ಣು (Nimbe)' } },
  ],
  'Common Objects': [
    { emoji: '📚', english: 'Book', translations: { hindi: 'किताब (Kitab)', tamil: 'புத்தகம் (Puttakam)', telugu: 'పుस्तకం (Pustakaṁ)', kannada: 'ಪುಸ್ತಕ (Pustaka)' }, image: '/vocab_book.png' },
    { emoji: '🔑', english: 'Key', translations: { hindi: 'चाबी (Chabi)', tamil: 'சாவி (Cāvi)', telugu: 'తాళం (Tāḷaṁ)', kannada: 'ಕೀಲಿ (Kīli)' } },
    { emoji: '🖊️', english: 'Pen', translations: { hindi: 'कलम (Kalam)', tamil: 'பேனா (Pēṉā)', telugu: 'పెన్ (Pen)', kannada: 'ಪೆನ್ (Pen)' } },
    { emoji: '📱', english: 'Phone', translations: { hindi: 'मोबाइल (Mobile)', tamil: 'கைபேசி (Kaipeci)', telugu: 'ఫోన్ (Phōn)', kannada: 'ಮೊಬೈಲ್ (Mobile)' } },
    { emoji: '👓', english: 'Glasses', translations: { hindi: 'चश्मा (Chashma)', tamil: 'கண்ணாடி (Kaṇṇāṭi)', telugu: 'కళ్ళజోడు (Kaḷḷajōḍu)', kannada: 'ಕನ್ನಡಕ (Kannaḍaka)' } },
    { emoji: '🪑', english: 'Chair', translations: { hindi: 'कुर्सी (Kursi)', tamil: 'நாற்காலி (Nāṟkāli)', telugu: 'कुर्सी (Kursi)', kannada: 'ಕುರ್ಚಿ (Kurci)' } },
    { emoji: '🪵', english: 'Table', translations: { hindi: 'मेज (Mej)', tamil: 'மேஜை (Mējai)', telugu: 'బల్ల (Balla)', kannada: 'ಮೇಜು (Mēju)' } },
    { emoji: '🚪', english: 'Door', translations: { hindi: 'दरवाजा (Darwaza)', tamil: 'கதவு (Katavu)', telugu: 'ద్వారం (Dvāraṁ)', kannada: 'ಬಾಗಿಲು (Bāgilu)' } },
    { emoji: '🪟', english: 'Window', translations: { hindi: 'खिड़की (Khidki)', tamil: 'ஜன்னல் (Cannal)', telugu: 'కిటికీ (Kiṭikī)', kannada: 'ಕಿಟಕಿ (Kiṭaki)' } },
    { emoji: '⏰', english: 'Clock', translations: { hindi: 'घड़ी (Ghadi)', tamil: 'கடிகாரம் (Kaṭikāram)', telugu: 'గడియారం (Gaḍiyāraṁ)', kannada: 'ಗಡಿಯಾರ (Gaḍiyāra)' } },
    { emoji: '🪞', english: 'Mirror', translations: { hindi: 'दर्पण / शीशा', tamil: 'கண்ணாடி (Kaṇṇāṭi)', telugu: 'అద్దం (Addaṁ)', kannada: 'ಕನ್ನಡಿ (Kannadi)' } },
    { emoji: '☕', english: 'Cup', translations: { hindi: 'प्याला (Cup)', tamil: 'கோப்பை (Kōppai)', telugu: 'కప్పు (Kappu)', kannada: 'ಕಪ್ (Cup)' } },
    { emoji: '🍽️', english: 'Plate', translations: { hindi: 'थाली (Thali)', tamil: 'தட்டு (Taṭṭu)', telugu: 'పళ్లెం (Paḷḷeṁ)', kannada: 'ತಟ್ಟೆ (Taṭṭe)' } },
    { emoji: '🥄', english: 'Spoon', translations: { hindi: 'चम्मच (Chammach)', tamil: 'கரண்டி (Karaṇṭi)', telugu: 'చెంచా (Cenčā)', kannada: 'ಚಮಚ (Camaca)' } },
    { emoji: '🎒', english: 'Bag', translations: { hindi: 'बस्ता (Bag)', tamil: 'பை (Pai)', telugu: 'సంచి (Sanči)', kannada: 'ಚೀಲ (Cīla)' } },
  ],
  'Animals': [
    { emoji: '🐶', english: 'Dog', translations: { hindi: 'कुत्ता (Kutta)', tamil: 'நாய் (Nāy)', telugu: 'కుక్క (Kukka)', kannada: 'ನಾಯಿ (Nāyi)' } },
    { emoji: '🐱', english: 'Cat', translations: { hindi: 'बिल्ली (Billi)', tamil: 'பூனை (Pūṉai)', telugu: 'పిల్లి (Pilli)', kannada: 'ಬೆಕ್ಕು (Bekku)' } },
    { emoji: '🐮', english: 'Cow', translations: { hindi: 'गाय (Gaay)', tamil: 'பசு (Pacu)', telugu: 'ఆవు (Āvu)', kannada: 'ಹಸು (Hasu)' } },
    { emoji: '🦁', english: 'Lion', translations: { hindi: 'शेर (Sher)', tamil: 'சிங்கம் (Ciṅkam)', telugu: 'సింహం (Siṁhaṁ)', kannada: 'ಸಿಂಹ (Siṁha)' } },
    { emoji: '🐯', english: 'Tiger', translations: { hindi: 'बाघ (Baagh)', tamil: 'புலி (Puli)', telugu: 'పులి (Puli)', kannada: 'ಹುಲಿ (Huli)' } },
    { emoji: '🐘', english: 'Elephant', translations: { hindi: 'हाथी (Haathi)', tamil: 'யானை (Yāṉai)', telugu: 'ఏనుగు (Ēnugu)', kannada: 'ಆನೆ (Āne)' } },
    { emoji: '🐴', english: 'Horse', translations: { hindi: 'घोड़ा (Ghoda)', tamil: 'குதிரை (Kutirai)', telugu: 'గుర్రం (Gurraṁ)', kannada: 'ಕುದುರೆ (Kudure)' } },
    { emoji: '🐦', english: 'Bird', translations: { hindi: 'चिड़िया (Chidiya)', tamil: 'பறவை (Paṟavai)', telugu: 'పక్షి (Pakṣi)', kannada: 'ಪಕ್ಷಿ (Pakṣi)' } },
    { emoji: '🐟', english: 'Fish', translations: { hindi: 'मछली (Machhli)', tamil: 'மீன் (Mīn)', telugu: 'చేప (Cēpa)', kannada: 'ಮೀನು (Mīnu)' } },
    { emoji: '🐑', english: 'Sheep', translations: { hindi: 'भेड़ (Bhed)', tamil: 'செம்மறியாடு', telugu: 'గొర్రె (Gorre)', kannada: 'ಕುರಿ (Kuri)' } },
    { emoji: '🐐', english: 'Goat', translations: { hindi: 'बकरी (Bakri)', tamil: 'ஆடு (Āṭu)', telugu: 'మేక (Mēka)', kannada: 'ಮೇಕೆ (Mēke)' } },
    { emoji: '🐒', english: 'Monkey', translations: { hindi: 'बंदर (Bandar)', tamil: 'குரங்கு (Kuraṅku)', telugu: 'కోతి (Kōti)', kannada: 'ಕೋತಿ (Kōti)' } },
    { emoji: '🐇', english: 'Rabbit', translations: { hindi: 'खरगोश (Khargosh)', tamil: 'முயல் (Muyal)', telugu: 'కుందేలు (Kundēlu)', kannada: 'ಮೊಲ (Mola)' } },
    { emoji: '🦆', english: 'Duck', translations: { hindi: 'बतख (Batakh)', tamil: 'வாத்து (Vāttu)', telugu: 'ಬಾತುಕೋಳಿ (Bātukōḷi)', kannada: 'ಬಾತುಕೋಳಿ' } },
    { emoji: '🐔', english: 'Chicken', translations: { hindi: 'मुर्गी (Murgi)', tamil: 'கோழி (Kōḻi)', telugu: 'కోడి (Kōḍi)', kannada: 'ಕೋಳಿ (Kōḷi)' } },
  ],
  'Public Places': [
    { emoji: '🏥', english: 'Hospital', translations: { hindi: 'अस्पताल (Aspatal)', tamil: 'மருத்துவமனை (Maruttuvamaṉai)', telugu: 'ఆసుპత్రి (Āsupatri)', kannada: 'ಆಸ್ಪತ್ರೆ (Āspatre)' }, image: '/vocab_hospital.png' },
    { emoji: '🏫', english: 'School', translations: { hindi: 'स्कूल (School)', tamil: 'பள்ளி (Paḷḷi)', telugu: 'పాఠశాల (Pāṭhaśāla)', kannada: 'ಶಾಲೆ (Śāle)' } },
    { emoji: '🏪', english: 'Shop', translations: { hindi: 'दुकान (Dukan)', tamil: 'கடை (Kaṭai)', telugu: 'దుకాణం (Dukāṇaṁ)', kannada: 'ಅಂಗಡಿ (Aṅgaḍi)' } },
    { emoji: '🌳', english: 'Park', translations: { hindi: 'उद्यान / पार्क', tamil: 'பூங்கா (Pūṅkā)', telugu: 'ఉద్యానవనం (Udyānavanaṁ)', kannada: 'ಉದ್ಯಾನ (Udyāna)' } },
    { emoji: '🏦', english: 'Bank', translations: { hindi: 'बैंक (Bank)', tamil: 'வங்கி (Vaṅki)', telugu: 'బ్యాంకు (Byāṅku)', kannada: 'ಬ್ಯಾಂಕ್ (Bank)' } },
    { emoji: '📮', english: 'Post Office', translations: { hindi: 'डाकघर (Post Office)', tamil: 'தபால் நிலையம்', telugu: 'పోస్టాఫీసు', kannada: 'ಅಂಚೆ ಕಚೇರಿ' } },
    { emoji: '🚉', english: 'Station', translations: { hindi: 'स्टेशन (Station)', tamil: 'நிலையம் (Nilaiyam)', telugu: 'స్టేషన్ (Stēṣan)', kannada: 'ನಿಲ್ದಾಣ (Nildāṇa)' } },
    { emoji: '📚', english: 'Library', translations: { hindi: 'पुस्तकालय', tamil: 'நூலகம் (Nūlakam)', telugu: 'గ్రంథాలయం', kannada: 'ಗ್ರಂಥಾಲಯ (Granthālaya)' } },
    { emoji: '🛍️', english: 'Market', translations: { hindi: 'बाज़ार (Bazaar)', tamil: 'சந்தை (Cantai)', telugu: 'మార్కెట్ (Mārkeṭ)', kannada: 'ಮಾರುಕಟ್ಟೆ (Mārukaṭṭe)' } },
    { emoji: '🛕', english: 'Temple', translations: { hindi: 'मंदिर (Mandir)', tamil: 'கோவில் (Kōvil)', telugu: 'గుడి (Guḍi)', kannada: 'ದೇವಸ್ಥಾನ (Dēvasthāna)' } },
    { emoji: '🍽️', english: 'Restaurant', translations: { hindi: 'भोजनालय (Hotel)', tamil: 'உணவகம் (Uṇavakam)', telugu: 'హోటల్ (Hōṭal)', kannada: 'ಉಪಹಾರ ಗೃಹ (Hotel)' } },
    { emoji: '🏢', english: 'Office', translations: { hindi: 'कार्यालय (Office)', tamil: 'அலுவலகம் (Aluvalakam)', telugu: 'కార్యాలయం (Kāryālayaṁ)', kannada: 'ಕಚೇರಿ (Kacēri)' } },
    { emoji: '🚏', english: 'Bus Stop', translations: { hindi: 'बस स्टॉप', tamil: 'பேருந்து நிறுத்தம்', telugu: 'బస్ స్టాప్', kannada: 'ಬಸ್ ನಿಲ್ದಾಣ' } },
    { emoji: '✈️', english: 'Airport', translations: { hindi: 'हवाई अड्डा', tamil: 'விமான நிலையம்', telugu: 'విమానాశ్రయం', kannada: 'ವಿಮಾನ ನಿಲ್ದಾಣ' } },
    { emoji: '🚓', english: 'Police Station', translations: { hindi: 'थाना (Police Station)', tamil: 'காவல் நிலையம்', telugu: 'పోలీస్ స్టేషన్', kannada: 'ಪೊಲೀಸ್ ಠಾಣೆ' } },
  ],
  'Action Words': [
    { emoji: '🏃‍♂️', english: 'Run', translations: { hindi: 'दौड़ना (Daudna)', tamil: 'ஓடு (Ōṭu)', telugu: 'పరుగెత్తు (Parugettu)', kannada: 'ಓಡು (Ōḍu)' } },
    { emoji: '🚶‍♂️', english: 'Walk', translations: { hindi: 'चलना (Chalna)', tamil: 'நட (Naṭa)', telugu: 'నడువు (Naḍuvu)', kannada: 'ನಡೆ (Nade)' } },
    { emoji: '🦘', english: 'Jump', translations: { hindi: 'कूदना (Koodna)', tamil: 'குதி (Kuti)', telugu: 'దూకు (Dūku)', kannada: 'ခုದಿ (Kudi)' } },
    { emoji: '📖', english: 'Read', translations: { hindi: 'पढ़ना (Padhna)', tamil: 'படி (Paṭi)', telugu: 'చదువు (Čaduvu)', kannada: 'ಓದು (Ōdu)' } },
    { emoji: '✍️', english: 'Write', translations: { hindi: 'लिखना (Likhna)', tamil: 'எழுது (Eḻutu)', telugu: 'రాయు (Rāyu)', kannada: 'ಬರೆ (Bare)' } },
    { emoji: '🗣️', english: 'Speak', translations: { hindi: 'बोलना (Bolna)', tamil: 'பேசு (Pēcu)', telugu: 'మాట్లాడు (Māṭlāḍu)', kannada: 'ಮಾತನಾಡು (Mātanāḍu)' } },
    { emoji: '🍎', english: 'Eat', translations: { hindi: 'खाना (Khana)', tamil: 'சாப்பிடு (Cāppiṭu)', telugu: 'తిను (Tinu)', kannada: 'ತಿನ್ನು (Tinnu)' } },
    { emoji: '🥤', english: 'Drink', translations: { hindi: 'पीना (Peena)', tamil: 'குடி (Kuṭi)', telugu: 'త్రాగు (Trāgu)', kannada: 'ಕುಡಿ (Kuḍi)' } },
    { emoji: '😴', english: 'Sleep', translations: { hindi: 'सोना (Sona)', tamil: 'தூங்கு (Tūṅku)', telugu: 'నిద్రించు (Nidrinču)', kannada: 'ಮಲಗು (Malagu)' } },
    { emoji: '⚽', english: 'Play', translations: { hindi: 'खेलना (Khelna)', tamil: 'விளையாடு (Viḷaiyāṭu)', telugu: 'ఆడుకొను (Āḍukonu)', kannada: 'ಆಟವಾಡು (Āṭavāḍu)' } },
    { emoji: '💻', english: 'Code', translations: { hindi: 'कोडिंग करना', tamil: 'குறியீடு (Kuṟiyīṭu)', telugu: 'కోడింగ్ (Kōḍiṅg)', kannada: 'ಕೋಡಿಂಗ್ (Coding)' } },
    { emoji: '🎨', english: 'Draw', translations: { hindi: 'चित्र बनाना', tamil: 'வரை (Varai)', telugu: 'చిత్రించు (Čitrinču)', kannada: 'ಚಿತ್ರಿಸು (Citrisu)' } },
    { emoji: '🍳', english: 'Cook', translations: { hindi: 'पकाना (Pakana)', tamil: 'சமை (Camai)', telugu: 'వండు (Vaṇḍu)', kannada: 'ಅಡುಗೆ ಮಾಡು (Aḍuge)' } },
    { emoji: '🏊‍♂️', english: 'Swim', translations: { hindi: 'तैरना (Tairna)', tamil: 'நீந்து (Nīntu)', telugu: 'ఈదు (Īdu)', kannada: 'ಈಜು (Īju)' } },
    { emoji: '👂', english: 'Listen', translations: { hindi: 'सुनना (Sunna)', tamil: 'கேள் (Kēḷ)', telugu: 'विను (Vinu)', kannada: 'ಕೇಳು (Kēḷu)' } },
  ],
  'Family & People': [
    { emoji: '👩', english: 'Mother', translations: { hindi: 'माता / माँ (Maa)', tamil: 'அம்மா (Ammā)', telugu: 'తల్లి (Talli)', kannada: 'ತಾಯಿ (Tāyi)' } },
    { emoji: '👨', english: 'Father', translations: { hindi: 'पिता / पापा', tamil: 'அப்பா (Appā)', telugu: 'తండ్రి (Taṇḍri)', kannada: 'ತಂದೆ (Tande)' } },
    { emoji: '👦', english: 'Brother', translations: { hindi: 'भाई (Bhai)', tamil: 'சகோதரன் (Cakōtaraṉ)', telugu: 'సోదరుడు (Sōdaruḍu)', kannada: 'ಸಹೋದರ (Sahōdara)' } },
    { emoji: '👧', english: 'Sister', translations: { hindi: 'बहन (Behan)', tamil: 'சகோதரி (Cakōtari)', telugu: 'సోదరి (Sōdari)', kannada: 'ಸಹೋದರಿ (Sahōdari)' } },
    { emoji: '👶', english: 'Son', translations: { hindi: 'बेटा (Beta)', tamil: 'மகன் (Makaṉ)', telugu: 'కుమారుడు (Kumāruḍu)', kannada: 'ಮಗ (Maga)' } },
    { emoji: '🧒', english: 'Daughter', translations: { hindi: 'बेटी (Beti)', tamil: 'மகள் (Makaḷ)', telugu: 'కుమార్తె (Kumārte)', kannada: 'ಮಗಳು (Magaḷu)' } },
    { emoji: '🤝', english: 'Friend', translations: { hindi: 'दोस्त (Dost)', tamil: 'நண்பன் (Naṇpaṉ)', telugu: 'స్నేహితుడు (Snēhituḍu)', kannada: 'ಸ್ನೇಹಿತ (Snēhita)' } },
    { emoji: '👩‍🏫', english: 'Teacher', translations: { hindi: 'शिक्षक (Teacher)', tamil: 'ஆசிரியர் (Āciriyar)', telugu: 'ఉపాధ్యాయుడు', kannada: 'ಶಿಕ್ಷಕ (Śikṣaka)' } },
    { emoji: '🧑‍⚕️', english: 'Doctor', translations: { hindi: 'चिकित्सक / डॉक्टर', tamil: 'மருத்துவர் (Maruttuvar)', telugu: 'వైద్యుడు (Vaidyuḍu)', kannada: 'ವೈದ್ಯ (Vaidya)' } },
    { emoji: '🧑‍🌾', english: 'Farmer', translations: { hindi: 'किसान (Kisan)', tamil: 'விவசாயி (Vivacāyi)', telugu: 'రైతు (Raitu)', kannada: 'ರೈತ (Raita)' } },
    { emoji: '🧑‍🎓', english: 'Student', translations: { hindi: 'छात्र (Student)', tamil: 'மாணவன் (Māṇavaṉ)', telugu: 'విద్యార్థి (Vidyārthi)', kannada: 'ವಿದ್ಯಾರ್ಥಿ (Vidyārthi)' } },
    { emoji: '🚼', english: 'Baby', translations: { hindi: 'शिशु / बच्चा', tamil: 'குழந்தை (Kuḻantai)', telugu: 'పాప (Pāpa)', kannada: 'ಮಗು (Magu)' } },
    { emoji: '👴', english: 'Grandfather', translations: { hindi: 'दादा / नाना', tamil: 'தாத்தா (Tāttā)', telugu: 'తాతయ్య (Tātayya)', kannada: 'ತಾತ (Tāta)' } },
    { emoji: '👵', english: 'Grandmother', translations: { hindi: 'दादी / नानी', tamil: 'பாட்டி (Pāṭṭi)', telugu: 'నానమ్మ (Nānamma)', kannada: 'ಅಜ್ಜಿ (Ajji)' } },
    { emoji: '🏠', english: 'Neighbor', translations: { hindi: 'पड़ोसी (Padosi)', tamil: 'அண்டை வீட்டார்', telugu: 'పొరుగువారు', kannada: 'ನೆರೆಹೊರೆಯವರು' } },
  ],
  'Colors & Shapes': [
    { emoji: '🔴', english: 'Red', translations: { hindi: 'लाल (Laal)', tamil: 'சிவப்பு (Civappu)', telugu: 'ఎరుపు (Erupu)', kannada: 'ಕೆಂಪು (Kempu)' } },
    { emoji: '🔵', english: 'Blue', translations: { hindi: 'नीला (Neela)', tamil: 'நீலம் (Nīlam)', telugu: 'నీలం (Nīlaṁ)', kannada: 'ನೀಲಿ (Nīli)' } },
    { emoji: '🟢', english: 'Green', translations: { hindi: 'हरा (Hara)', tamil: 'பச்சை (Paccai)', telugu: 'ఆకుపచ్చ (Ākupacca)', kannada: 'ಹಸಿರು (Hasiru)' } },
    { emoji: '🟡', english: 'Yellow', translations: { hindi: 'पीला (Peela)', tamil: 'மஞ்சள் (Mañcaḷ)', telugu: 'పసుపు (Pasupu)', kannada: 'ಹಳದಿ (Haḷadi)' } },
    { emoji: '🟠', english: 'Orange', translations: { hindi: 'नारंगी (Narangi)', tamil: 'ஆரஞ்சு (Ārañcu)', telugu: 'నారింజ (Nāriṁja)', kannada: 'ಕಿತ್ತಳೆ (Kittaḷe)' } },
    { emoji: '⚫', english: 'Black', translations: { hindi: 'काला (Kaala)', tamil: 'கருப்பு (Karuppu)', telugu: 'నలుపు (Nalupu)', kannada: 'ಕಪ್ಪು (Kappu)' } },
    { emoji: '⚪', english: 'White', translations: { hindi: 'सफ़ेद (Safed)', tamil: 'வெள்ளை (Veḷḷai)', telugu: 'తెలుపు (Telupu)', kannada: 'ಬಿಳಿ (Biḷi)' } },
    { emoji: '⭕', english: 'Circle', translations: { hindi: 'वृत्त / गोला', tamil: 'வட்டம் (Vaṭṭam)', telugu: 'వృత్తం (Vṛttaṁ)', kannada: 'ವೃತ್ತ (Vṛtta)' } },
    { emoji: '🟩', english: 'Square', translations: { hindi: 'वर्ग (Varg)', tamil: 'சதுரம் (Caturam)', telugu: 'చతురస్రం (Čaturasraṁ)', kannada: 'ಚೌಕ (Cauka)' } },
    { emoji: '🔺', english: 'Triangle', translations: { hindi: 'त्रिकोण (Trikon)', tamil: 'முக்கோணம் (Mukkōṇam)', telugu: 'త్రికోణం (Trikōṇaṁ)', kannada: 'ತ್ರಿಕೋನ (Trikōna)' } },
  ],
  'Numbers & Time': [
    { emoji: '1️⃣', english: 'One', translations: { hindi: 'एक (Ek)', tamil: 'ஒன்று (Oṉṟu)', telugu: 'ఒకటి (Okaṭi)', kannada: 'ಒಂದು (Ondu)' } },
    { emoji: '2️⃣', english: 'Two', translations: { hindi: 'दो (Do)', tamil: 'இரண்டு (Iraṇṭu)', telugu: 'రెండు (Reṇḍu)', kannada: 'ಎರಡು (Eraḍu)' } },
    { emoji: '3️⃣', english: 'Three', translations: { hindi: 'तीन (Teen)', tamil: 'மூன்று (Mūṉṟu)', telugu: 'మూడు (Mūḍu)', kannada: 'ಮೂರು (Mūru)' } },
    { emoji: '4️⃣', english: 'Four', translations: { hindi: 'चार (Chaar)', tamil: 'நான்கு (Nāṉku)', telugu: 'నాలుగు (Nālugu)', kannada: 'ನಾಲ್ಕು (Nālku)' } },
    { emoji: '5️⃣', english: 'Five', translations: { hindi: 'पाँच (Paanch)', tamil: 'ஐந்து (Aintu)', telugu: 'ಐದು (Aidu)', kannada: 'ಐದು (Aidu)' } },
    { emoji: '☀️', english: 'Day', translations: { hindi: 'दिन (Din)', tamil: 'பகல் / நாள்', telugu: 'పగలు (Pagalu)', kannada: 'ಹಗಲು (Hagalu)' } },
    { emoji: '🌙', english: 'Night', translations: { hindi: 'रात (Raat)', tamil: 'இரவு (Iravu)', telugu: 'రాత్రి (Rātri)', kannada: 'ರಾತ್ರಿ (Rātri)' } },
    { emoji: '🌅', english: 'Morning', translations: { hindi: 'सुबह (Subah)', tamil: 'காலை (Kālai)', telugu: 'ఉదయం (Udayaṁ)', kannada: 'ಬೆಳಿಗ್ಗೆ (Beḷigge)' } },
    { emoji: '🌇', english: 'Evening', translations: { hindi: 'शाम (Shaam)', tamil: 'மாலை (Mālai)', telugu: 'సాయంత్రం (Sāyaṁtraṁ)', kannada: 'ಸಂಜೆ (Sañje)' } },
    { emoji: '📅', english: 'Year', translations: { hindi: 'वर्ष / साल', tamil: 'வருடம் (Varuṭam)', telugu: 'సంవత్సరం', kannada: 'ವರ್ಷ (Varṣa)' } },
  ]
};
