# Generated by Django 6.0.6 on 2026-07-06 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_language',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('age', models.CharField(default='24', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(default='Primary School', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('preferredLanguage', models.CharField(default='english', max_length=50)),
                ('learningGoal', models.CharField(blank=True, max_length=200, null=True)),
                ('readingLevel', models.CharField(default='Beginner', max_length=50)),
                ('writingLevel', models.CharField(default='Beginner', max_length=50)),
                ('speakingConfidence', models.CharField(default='50', max_length=10)),
                ('dailyLearningTime', models.CharField(default='30 mins', max_length=50)),
                ('avatar', models.CharField(default='🧑\u200d🎓', max_length=50)),
                ('xp', models.IntegerField(default=10)),
                ('coins', models.IntegerField(default=10)),
                ('streak', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('badges', models.TextField(default='[]')),
                ('completedLessons', models.TextField(default='[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
