# Generated by Django 6.0.6 on 2026-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parentEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pushSubscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
