# Generated by Django 6.0.6 on 2026-07-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_curriculum_lesson_imageurl_lesson_curriculum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(default=list)),
                ('weak_skills_detected', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text', models.TextField(default='')),
                ('learner_transcript', models.TextField(default='')),
                ('content_score', models.IntegerField(default=85)),
                ('pronunciation_score', models.IntegerField(default=85)),
                ('fluency_score', models.IntegerField(default=88)),
                ('speech_rate', models.IntegerField(default=120)),
                ('pause_count', models.IntegerField(default=1)),
                ('overall_score', models.IntegerField(default=86)),
                ('result_label', models.CharField(default='Good', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_scores', to='curriculum.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('transcript', models.TextField()),
                ('confidence', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_attempts', to='curriculum.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=100)),
                ('coins', models.IntegerField(default=50)),
                ('streak_days', models.IntegerField(default=3)),
                ('last_login_date', models.DateField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('badges', models.JSONField(default=list)),
                ('claimed_rewards', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
